"""
run_broken_agents.py  —  VIGIL Broken-Agent Evaluation Driver
==============================================================
Runs each intentionally broken agent codebase, collects its logs,
then invokes the full VIGIL pipeline (reflect → diagnose → prompt patch → code proposal).

VIGIL will:
  1. Read the agent's event logs (generated by the broken agent itself)
  2. Scan the agent's source code (the broken agent.py) for hotspots
  3. Produce prompt patches and unified diffs targeting the real bugs

Usage:
    python run_broken_agents.py                  # all 6 agents
    python run_broken_agents.py --agent robin_a  # single agent
    python run_broken_agents.py --sessions 20    # more sessions for richer logs
    python run_broken_agents.py --dry-run        # generate logs only, skip VIGIL

Outputs per agent (in output/<agent>/):
    logs/events.jsonl           — the agent's own failure logs
    new_prompt.txt              — VIGIL's patched prompt
    proposals/LLM_patch_*.diff  — unified diff targeting the broken code
    proposals/LLM_PR_*.md       — PR description with diagnosis rationale
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE = Path(__file__).parent.resolve()       # broken_agents/
AGENTS_DIR = HERE                            # agents live alongside this script
VIGIL_ROOT = HERE.parent                     # one level up = vigil repo root
SCAFFOLD = VIGIL_ROOT / "robin_b_project_scaffold"

for p in (str(VIGIL_ROOT), str(SCAFFOLD)):
    if p not in sys.path:
        sys.path.insert(0, p)

# ---------------------------------------------------------------------------
# Agent registry
# ---------------------------------------------------------------------------
AGENTS = {
    "robin_a": {
        "dir":         AGENTS_DIR / "robin_a",
        "module":      "reminders",
        "run_fn":      "run_session",
        "run_kwargs":  {"n": 12},
        "description": "Reminder scheduling — naive timestamps, premature toasts, duplicate retries",
    },
    "robin_cs": {
        "dir":         AGENTS_DIR / "robin_cs",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Customer service — fake sentiment, no escalation, unauthorized discounts",
    },
    "robin_pa": {
        "dir":         AGENTS_DIR / "robin_pa",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Personal planner — context amnesia, premature confirms, no conflict detection",
    },
    "robin_dev": {
        "dir":         AGENTS_DIR / "robin_dev",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Coding agent — no file hashing, blind patches, no regression detection",
    },
    "robin_rag": {
        "dir":         AGENTS_DIR / "robin_rag",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "RAG research — no relevance threshold, fake citations, overconfident answers",
    },
    "robin_etl": {
        "dir":         AGENTS_DIR / "robin_etl",
        "module":      "agent",
        "run_fn":      "run_batches",
        "run_kwargs":  {"n": 12},
        "description": "ETL pipeline — stale data, no schema validation, no idempotency, silent corruption",
    },
    "robin_auth": {
        "dir":         AGENTS_DIR / "robin_auth",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Auth — expired tokens accepted, rate limit never blocks, timing-unsafe compare",
    },
    "robin_payment": {
        "dir":         AGENTS_DIR / "robin_payment",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Payments — no idempotency key, refund without original, stale FX rate, float rounding",
    },
    "robin_notification": {
        "dir":         AGENTS_DIR / "robin_notification",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Notifications — opt-out not enforced, no backoff on retry, missing dedup key",
    },
    "robin_search": {
        "dir":         AGENTS_DIR / "robin_search",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Search — deleted docs returned, results not sorted by score, no schema validation",
    },
    "robin_inventory": {
        "dir":         AGENTS_DIR / "robin_inventory",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Inventory — oversell via negative stock, reorder alert fires after stockout",
    },
    "robin_analytics": {
        "dir":         AGENTS_DIR / "robin_analytics",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Analytics — PII in raw logs, duplicate events, hardcoded anomaly threshold",
    },
    "robin_email": {
        "dir":         AGENTS_DIR / "robin_email",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Email — no address validation, XSS in HTML, no unsubscribe header, oversized attachments",
    },
    "robin_cache": {
        "dir":         AGENTS_DIR / "robin_cache",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Cache — TTL never enforced, stampede unprotected, tz in cache key, wrong shard purge",
    },
    "robin_scheduler": {
        "dir":         AGENTS_DIR / "robin_scheduler",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Scheduler — duplicate job IDs, priority ignored, no timeout, no dead-letter queue",
    },
    "robin_monitor": {
        "dir":         AGENTS_DIR / "robin_monitor",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Monitor — alert storms, severity case mismatch, stale workers not evicted",
    },
    "robin_webhook": {
        "dir":         AGENTS_DIR / "robin_webhook",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Webhooks — HMAC sig not sent, fixed retry delay, disabled endpoints not checked",
    },
    "robin_nlp": {
        "dir":         AGENTS_DIR / "robin_nlp",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "NLP — low-confidence results passed through, toxic content not gated, no model version",
    },
    "robin_media": {
        "dir":         AGENTS_DIR / "robin_media",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Media — original deleted before transcode confirmed, no checksum, GPS exif leak",
    },
    "robin_recommendation": {
        "dir":         AGENTS_DIR / "robin_recommendation",
        "module":      "agent",
        "run_fn":      "run_sessions",
        "run_kwargs":  {"n": 12},
        "description": "Recommendations — blocklist not filtered, negative scores, stale embeddings",
    },
}


# ---------------------------------------------------------------------------
# Step 1: Run the broken agent to generate logs
# ---------------------------------------------------------------------------

def generate_agent_logs(agent_name: str, cfg: dict, out_dir: Path, sessions: int) -> Path:
    logs_dir = out_dir / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_path = logs_dir / "events.jsonl"

    # Clear existing logs
    if log_path.exists():
        log_path.unlink()

    # Point agent's log output to our directory
    os.environ["EVENTS_LOG"] = str(log_path)

    # Dynamically load and run the broken agent module
    agent_dir = cfg["dir"]
    module_file = agent_dir / f"{cfg['module']}.py"

    spec = importlib.util.spec_from_file_location(
        f"broken_{agent_name}", str(module_file)
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    run_fn = getattr(mod, cfg["run_fn"])
    kwargs = dict(cfg["run_kwargs"])
    # Override session/batch count if --sessions specified
    for k in ("n", "sessions", "batches"):
        if k in kwargs:
            kwargs[k] = sessions

    run_fn(**kwargs)

    n_events = sum(1 for l in log_path.read_text().splitlines() if l.strip())
    return log_path, n_events


# ---------------------------------------------------------------------------
# Step 2: Run VIGIL pipeline on the broken agent's logs + source
# ---------------------------------------------------------------------------

def run_vigil_on_agent(agent_name: str, cfg: dict, log_path: Path, out_dir: Path) -> dict:
    import sys
    from robin_b_project_scaffold.robin_b.RobinBAgent.orchestrator import run_once, SESSION
    from robin_b_project_scaffold.robin_b.b_core import emobank as _emo

    # Reset stage machine
    SESSION["stage"] = "start"

    # Resolve to absolute paths BEFORE chdir — relative paths break after chdir
    log_path_abs    = log_path.resolve()
    out_dir_abs     = out_dir.resolve()
    agent_py        = cfg["dir"] / "agent.py"
    prompt_path_abs = (out_dir_abs / "agent_prompt.py")
    repo_root_abs   = Path(cfg["dir"]).resolve()

    # Isolate EmoBank to this agent's output dir
    emo_dir = out_dir_abs / "db" / "emobank"
    emo_dir.mkdir(parents=True, exist_ok=True)
    (out_dir_abs / "output" / "proposals").mkdir(parents=True, exist_ok=True)

    # Collect ALL emobank module references in sys.modules — relative and absolute
    # imports produce separate entries and we must patch every one.
    emo_modules = {
        key: mod for key, mod in sys.modules.items()
        if "emobank" in key and hasattr(mod, "ROOT")
    }

    # Save originals and patch all of them
    originals = {}
    for key, mod in emo_modules.items():
        originals[key] = {
            "ROOT":       mod.ROOT,
            "PATH_EMO":   mod.PATH_EMO,
            "PATH_STATE": mod.PATH_STATE,
            "PATH_INDEX": getattr(mod, "PATH_INDEX", None),
        }
        mod.ROOT       = str(emo_dir)
        mod.PATH_EMO   = str(emo_dir / "emotions.jsonl")
        mod.PATH_STATE = str(emo_dir / "state.json")
        if hasattr(mod, "PATH_INDEX"):
            mod.PATH_INDEX = str(emo_dir / "index.json")

    shutil.copy(agent_py, prompt_path_abs)

    orig_cwd = os.getcwd()
    os.chdir(out_dir_abs)

    try:
        t0 = time.time()
        result = run_once(
            logs_path=str(log_path_abs),
            agent_prompt_path=str(prompt_path_abs),
            repo_root=str(repo_root_abs),
        )
        result["elapsed_s"] = round(time.time() - t0, 1)
    except Exception as e:
        result = {"text": "", "error": str(e), "elapsed_s": 0}

    # Deterministic fallback — if LLM skipped emit_unified_diff/save_proposal,
    # run propose() directly so artifacts are always produced.
    proposals_dir = out_dir_abs / "output" / "proposals"
    has_diff = any(proposals_dir.glob("*.diff")) if proposals_dir.exists() else False
    if not has_diff:
        try:
            from robin_b_project_scaffold.robin_b.runtime.b_propose import propose
            os.chdir(out_dir_abs)
            propose(
                logs_path=str(log_path_abs),
                repo_root=str(repo_root_abs),
                agent_prompt_relpath="agent.py",
                window_hours=24,
                apply_prompt=False,
            )
            result["fallback_propose"] = True
        except Exception as fe:
            result["fallback_error"] = str(fe)
        finally:
            os.chdir(orig_cwd)
    finally:
        os.chdir(orig_cwd)
        # Restore all emobank modules
        for key, mod in emo_modules.items():
            orig = originals[key]
            mod.ROOT       = orig["ROOT"]
            mod.PATH_EMO   = orig["PATH_EMO"]
            mod.PATH_STATE = orig["PATH_STATE"]
            if orig["PATH_INDEX"] is not None:
                mod.PATH_INDEX = orig["PATH_INDEX"]

    return result


# ---------------------------------------------------------------------------
# Step 3: Print a summary of what VIGIL found
# ---------------------------------------------------------------------------

def print_summary(agent_name: str, cfg: dict, log_path: Path, vigil_result: dict, out_dir: Path):
    print(f"\n{'='*60}")
    print(f"  {agent_name.upper()}: {cfg['description']}")
    print(f"{'='*60}")

    # Count failure events in logs
    fail_kinds = {}
    for line in log_path.read_text().splitlines():
        if not line.strip():
            continue
        try:
            ev = json.loads(line)
            if ev.get("status") in ("fail", "delay", "error"):
                k = ev.get("kind", "unknown")
                fail_kinds[k] = fail_kinds.get(k, 0) + 1
        except Exception:
            pass

    print(f"  Failure events by kind:")
    for kind, count in sorted(fail_kinds.items(), key=lambda x: -x[1]):
        print(f"    {kind:<35} {count:>4} events")

    if vigil_result.get("error"):
        print(f"\n  VIGIL ERROR: {vigil_result['error'][:200]}")
    else:
        print(f"\n  VIGIL completed in {vigil_result.get('elapsed_s', '?')}s")

    # List output artifacts
    proposals = out_dir / "output" / "proposals"
    if proposals.exists():
        diffs = list(proposals.glob("*.diff"))
        prs   = list(proposals.glob("*.md"))
        print(f"  Artifacts: {len(diffs)} diff(s), {len(prs)} PR(s) in {proposals}")

    new_prompt = out_dir / "output" / "new_prompt.txt"
    if new_prompt.exists():
        print(f"  Patched prompt: {new_prompt}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Run broken agents and invoke VIGIL")
    parser.add_argument("--agent",    choices=list(AGENTS.keys()), default=None,
                        help="Run a single agent (default: all)")
    parser.add_argument("--sessions", type=int, default=12,
                        help="Number of sessions/batches to generate (default: 12)")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Generate logs only — skip VIGIL pipeline")
    parser.add_argument("--out-dir",  default="broken_agent_output",
                        help="Root output directory (default: broken_agent_output/)")
    args = parser.parse_args()

    agents_to_run = {args.agent: AGENTS[args.agent]} if args.agent else AGENTS
    out_root = Path(args.out_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    print(f"VIGIL Broken-Agent Eval")
    print(f"Agents: {list(agents_to_run.keys())}")
    print(f"Sessions per agent: {args.sessions}")
    print(f"Output root: {out_root}\n")

    for agent_name, cfg in agents_to_run.items():
        print(f"\n[{agent_name}] Generating logs from broken codebase...")
        out_dir = out_root / agent_name
        out_dir.mkdir(exist_ok=True)

        try:
            log_path, n_events = generate_agent_logs(agent_name, cfg, out_dir, args.sessions)
            print(f"  → {n_events} events written to {log_path}")
        except Exception as e:
            print(f"  [ERROR] Log generation failed: {e}")
            continue

        if args.dry_run:
            print(f"  [dry-run] Skipping VIGIL pipeline.")
            continue

        print(f"  Running VIGIL pipeline (LLM calls — takes ~1-3 min)...")
        vigil_result = run_vigil_on_agent(agent_name, cfg, log_path, out_dir)
        print_summary(agent_name, cfg, log_path, vigil_result, out_dir)

    print(f"\n\nAll done. Outputs in: {out_root.resolve()}/")
    print("Per-agent outputs:")
    for agent_name in agents_to_run:
        d = out_root / agent_name
        print(f"  {agent_name}: {d}/")


if __name__ == "__main__":
    main()
